
CREATE TABLE HR.PH_CUSTOMER (
CUSTOMER_ID NUMBER(15) NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR2(100) NOT NULL,
MIDDLE_NAME VARCHAR2(100),
LAST_NAME VARCHAR2(100) NOT NULL,
CREATE_USER VARCHAR2(200),
CREATE_TIMESTAMP DATE)

CREATE TABLE HR.PH_CUSTOMER_EMAIL (
CUSTOMER_EMAIL_ID NUMBER(15) NOT NULL PRIMARY KEY,
CUSTOMER_ID NUMBER(15),
EMAIL_ID VARCHAR2(100) NOT NULL,
EMAIL_TYPE VARCHAR2(100),
IS_PRIMARY_EMAIL CHAR(1),
ACTIVE char(1),
CREATE_USER VARCHAR2(200),
CREATE_TIMESTAMP DATE)

CREATE TABLE HR.PH_CUSTOMER_CURRENT_ADDRESS(
CUSTOMER_ADDRESS_ID NUMBER(15) NOT NULL PRIMARY KEY,
CUSTOMER_ID NUMBER(15),
ADDRESS_LINE1 VARCHAR2(100) NOT NULL,
ADDRESS_LINE2 VARCHAR2(100),
LANDMARK VARCHAR2(100),
ADDRESS_TYPE VARCHAR2(100),
CITY VARCHAR2(100) NOT NULL,
STATE VARCHAR2(100) NOT NULL,
COUNTRY VARCHAR2(100),
ZIPCODE NUMBER(15),
IS_ACTIVE char(1),
CREATE_USER VARCHAR2(200),
CREATE_TIMESTAMP DATE)


CREATE TABLE HR.PH_CUSTOMER_PHONE(
CUSTOMER_PH_ID NUMBER(15) NOT NULL PRIMARY KEY,
CUSTOMER_ID NUMBER(15),
PHONE_TYPE  VARCHAR2(100),
PHONE_NO NUMBER(20),
IS_PRIMARY_PH  CHAR(1),
IS_ACTIVE  CHAR(1),
CREATE_USER VARCHAR2(200),
CREATE_TIMESTAMP DATE)

CREATE TABLE HR.PH_STORE(
STORE_ID NUMBER(15) NOT NULL PRIMARY KEY,
DISTRICT_ID NUMBER(15),
STORE_NAME VARCHAR2(100),
ADDRESS_LINE1 VARCHAR2(100) NOT NULL,
ADDRESS_LINE2 VARCHAR2(100),
LANDMARK VARCHAR2(100),
STORE_CITY VARCHAR2(100) NOT NULL,
STORE_ZIP NUMBER(20) NOT NULL,
STORE_PH NUMBER(20) NOT NULL,
STORE_HOURS VARCHAR2(100),
STORE_RATINGS NUMBER(10),
STORE_STATUS VARCHAR2(10),
STORE_START_DATE DATE,
CREATE_USER VARCHAR2(200),
CREATE_TIMESTAMP DATE)

CREATE TABLE HR.PH_DISTRICT (
DISTRICT_ID NUMBER(15) NOT NULL PRIMARY KEY,
DISTRICT_NAME VARCHAR2(100) NOT NULL,
STATE_NAME VARCHAR2(100) NOT NULL,
CREATE_USER VARCHAR2(200),
CREATE_TIMESTAMP DATE)

CREATE TABLE HR.PH_PRODUCT_CATEGORY(
CATEGORY_ID NUMBER(15) NOT NULL PRIMARY KEY,
CATEGORY_NAME  VARCHAR2(100) NOT NULL,
CATEGORY_DESC  VARCHAR2(100),
CREATE_USER VARCHAR2(200),
CREATE_TIMESTAMP DATE)

CREATE TABLE HR.PH_PRODUCT_SUB_CATEGORY(
SUB_CATEGORY_ID NUMBER(15) NOT NULL PRIMARY KEY,
CATEGORY_ID NUMBER(10),
SUB_CATEGORY_NAME VARCHAR2(100) NOT NULL,
SUB_CATEGORY_TYPE VARCHAR2(100),
SUB_CATEGORY_DESC VARCHAR2(250),
CREATE_USER VARCHAR2(200),
CREATE_TIMESTAMP DATE)


CREATE TABLE HR.PH_PRODUCT_DETAILS(
PRODUCT_ID NUMBER(15) NOT NULL PRIMARY KEY,
SUB_CATEGORY_ID NUMBER(15),
PRODUCT_PRICE NUMBER(20,2) NOT NULL,
PRODUCT_SIZE VARCHAR2(100),
PRODUCT_LAUNCH_DATE DATE NOT NULL,
NO_OF_CALORIES NUMBER(10),
PRODUCT_DESC VARCHAR2(250),
ALLERGENS_PRESENT CHAR(1),
PRODUCT_STATUS VARCHAR2(10),
CREATE_USER VARCHAR2(200),
CREATE_TIMESTAMP DATE)

CREATE TABLE HR.PH_PROMOTION(
PROMOTION_ID NUMBER(15) NOT NULL PRIMARY KEY,
PROMOTION_TYPE VARCHAR2(50),
PRMOTION_DESC VARCHAR2(250),
START_DATE DATE,
END_DATE DATE,
IS_ACTIVE CHAR(1),
CREATE_USER VARCHAR2(200),
CREATE_TIMESTAMP DATE)


CREATE TABLE HR.PH_PAYMENT_METHOD(
PAYMENT_ID NUMBER(15) NOT NULL PRIMARY KEY,
PAYMENT_DESC VARCHAR2(250),
PAYMENT_STATUS CHAR(1),
CREATE_USER VARCHAR2(200),
CREATE_TIMESTAMP DATE)

CREATE TABLE HR.PH_DELIVERY(
DELIVERY_ID NUMBER(15) NOT NULL PRIMARY KEY,
DELIVERY_TYPE VARCHAR2(50) NOT NULL,
DELIVERY_STATUS CHAR(1),
CREATE_USER VARCHAR2(200),
CREATE_TIMESTAMP DATE)

CREATE TABLE HR.PH_CHANNEL(
CHANNEL_ID NUMBER(15) NOT NULL PRIMARY KEY,
CHANNEL_TYPE VARCHAR2(50) NOT NULL,
CHANNEL_STATUS  CHAR(1),
CREATE_USER VARCHAR2(200),
CREATE_TIMESTAMP DATE)

CREATE TABLE HR.PH_ORDER(
ORDER_ID NUMBER(15) NOT NULL PRIMARY KEY,
CUSTOMER_ID  NUMBER(15),
ORDER_DATE DATE NOT NULL,
ORDER_STATUS CHAR(1),
STORE_ID  NUMBER(15),
ORDER_AMOUNT NUMBER(20,2),
TAX_AMOUNT NUMBER(10,2),
TOTAL_QTY NUMBER(10),
PAYMENT_ID  NUMBER(15),
DELIVERY_ID NUMBER(15),
CHANNEL_ID  NUMBER(15),
ORDER_FINAL_AMOUNT NUMBER(20,2),
CREATE_USER VARCHAR2(200),
CREATE_TIMESTAMP DATE)

CREATE TABLE HR.PH_ORDER_DETAILS(
ORDER_DETAILS_ID NUMBER(15) NOT NULL PRIMARY KEY,
ORDER_ID  NUMBER(15),
PRODUCT_ID NUMBER(15) ,
QUANTITY NUMBER(50),
PROMOTION_ID  NUMBER(15),
PRODUCT_PRICE NUMBER(20,2),
PROMOTION_DISCOUNT NUMBER(10,2),
PRODUCT_FINAL_PRICE NUMBER(20,2),
CREATE_USER VARCHAR2(200),
CREATE_TIMESTAMP DATE)































